### ISSUE TITLE
Windows 11 Recomendations don't work [BUG]: 

### ISSUE THREAD

**Issue by Konstantin202** [meetrevision/playbook#61] opened 2023-12-07 15:01 UTC
### Describe the bug

Windows startup menu recommendation, does not work... But I turned it on!

### Steps to reproduce

1. Install last 23.12 version. 

### Expected behavior

Trying to tunt it on, but it always off.

### Environment

- OS Build Number & Edition: `Windows 11 23h2`
- ReviOS Version: `Last version 23.12-4

### Have you searched for similar issues?

- [x] I have searched for similar issues and found none.

**Comment by StasiumDev** [comment] 2023-12-07 15:27
Could you elaborate what u mean?

**Comment by Konstantin202** [comment] 2023-12-07 16:05
![Screenshot 2023-12-07 190451](https://github.com/meetrevision/playbook/assets/90166922/f374d0b6-da41-4afe-b2f5-017a7f54b22e)
Recommended

**Comment by Konstantin202** [comment] 2023-12-08 07:44
I use 23.12-4 on two seperate windows 11 22h2, 23h2 clean installations with all last updates from microsoft, and both have the same problem.First was Windows 11 ReviOS-11-23.08.iso, second Windows Tiny 11 23h2.

**Comment by lovi-dzen** [comment] 2023-12-09 15:27
I have the same problem

**Comment by alexwrtq** [comment] 2024-01-05 09:11
Had the same problem on reviOS 23.12. The only fix i found is to downgrade to 23.10.

**Comment by alexwrtq** [comment] 2024-01-05 10:56
I had to clean install win11 and then apply 23.10 playbook.5 янв. 2024 г., в 11:29, lovi-dzen ***@***.***> написал(а):﻿
Very strange, because the same thing happened on version 23.10. Plus, if 23.12 was applied, how can I roll back? All settings are non-refundable. I think the recommendations have something to do with Windows Spotlight, which is broken due to closing and cutting.

**Comment by lovi-dzen** [comment] 2024-01-08 12:27
@alexwrtq Thanks for your observations, I hope the developers are checking the problem

**Comment by alexwrtq** [comment] 2024-01-14 08:57
Does the problem still exist? Really need to update to 23.12, but unless "Recommended" tab aren`t working don`t want to update.

**Comment by lovi-dzen** [comment] 2024-01-14 19:58
@alexwrtq The problem is still relevant; no updates or fixes have been released yet. Therefore, we are waiting for fixes in future versions

**Comment by melo936** [comment] 2024-02-01 07:17
I found a solution:

- Go to `C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy`
- Right click on `WsxPackManager.dll.bak`, Take ownership and rename it to `WsxPackManager.dll`
- Open **Task Manager** -> **Details**, select `StartMenuExperienceHost.exe` and click on the **End task** button at the top right corner
- Now simply click on the Windows button

Please let me know if it works.

**Comment by Konstantin202** [comment] 2024-02-01 07:27
@melo936 it works!

**Closed** 2024-02-02 07:55 UTC
Labels: bug, fixed, P4: Low
