### ISSUE TITLE
[FEATURE]: Can an offline version be made? In the area where I am, I cannot connect to the server to download files and cannot deploy.

### ISSUE THREAD

**Issue by aoy2024** [meetrevision/playbook#137] opened 2024-11-06 08:15 UTC
### Description

Can an offline version be made? In the area where I am, I cannot connect to the server to download files and cannot deploy.

### Benefit

Can an offline version be made? In the area where I am, I cannot connect to the server to download files and cannot deploy.

### Have you searched for similar feature requests?

- [X] I have searched for similar feature requests and found none.

**Comment by melo936** [comment] 2024-11-06 08:50
Duplicate of #72

**Closed by melo936** 2024-11-06 08:50 UTC
Labels: enhancement
